--- 

- name: UPDATE DES REPOS ET UPGRADE DE PAQUETS SUR TOUS LES SERVEURS 
  hosts: all    
  tags: always 
  become: true  
  pre_tasks:    
    - name: update index REPO et update des packages installés (RED HAT)
      dnf:
        update_cache: yes
        update_only: yes 
        state: latest
      when: ansible_facts['distribution'] == "RedHat" 
    - name: update index REPO et update des packages installés (UBUNTU)
      apt:
        update_cache: yes
        upgrade: full
      when: ansible_distribution == "Ubuntu" 

- name: DEPLOIEMENT FICHIER CUSTOM FACT SUR SERVEUR RHEL8-SRV1 
  hosts: rhel8-srv1 
  become: true
  tasks:
    - name: CREATION DU DOSSIER {{ path }} 
      file:              
        state: directory 
        recurse: yes     
        path: "{{ path }}"  
    - name: COPIE DU FICHIER CUSTOM FACT DANS LE DOSSIER facts.d
      copy:
        src: redhat_custom.fact
        dest: /etc/ansible/facts.d



- name: DEPLOIEMENT SERVEURS WEB   
  hosts: web_servers 
  become: true
  vars:              
    - apache: apache2
    - php: libapache2-mod-php
  tasks:
    - name: INSTALLATION {{ apache }} ET {{ php }} SUR LES SERVEURS WEB UBUNTU
      apt:               
        name:                      
          - "{{ apache }}"
          - "{{ php }}"
        state: latest
      when: ansible_distribution in ["Debian", "Ubuntu"] 
    - name: INSTALLATION APACHE(httpd) VIA CUSTOM FACTS ET INSTALLATION NORMALE PHP SUR LES SERVEURS WEB RED HAT
      dnf:                
        name: 
          - "{{ ansible_facts['ansible_local']['redhat_custom']['software']['package'] }}" 
          - php 
        state: latest 
      when: ansible_distribution == "RedHat" and ansible_distribution_version == "8.5" 
    - name: DEMARRER LE SERVICE HTTPD ET ACTIVER AU DEMARRAGE
      service:  
        name: "{{ ansible_facts['ansible_local']['redhat_custom']['software']['service'] }}" 
        state: "{{ ansible_facts['ansible_local']['redhat_custom']['software']['state'] }}" 
        enabled: "{{ ansible_facts['ansible_local']['redhat_custom']['software']['enabled'] }}"
      when: ansible_facts['distribution']== "RedHat"  
    - name: Autorisation des ports 80 et 443 sur FIREWALLD 
      ansible.posix.firewalld:
        port: "{{ item }}"  
        permanent: yes
        state: enabled
        immediate: yes
      loop:        
        - 80/tcp   
        - 443/tcp
      when: ansible_distribution == "RedHat"
    - name: COPIE DU FICHIER HTML VERS TOUS LES SERVEURS WEB
      copy:           
        src: default_site.html
        dest: /var/www/html/index.html 
        owner: root
        group: root
        mode: 0644 
      tags: copy
    - name: MODIFICATION DU MAIL DU SERVERADMIN DANS "httpd.conf" 
      lineinfile:   
        path: /etc/httpd/conf/httpd.conf 
        regexp: '^ServerAdmin'    
        line: ServerAdmin toto@mail.fr' 
      when: ansible_distribution == "RedHat"
      register: fichierhttpd 
    - name: AFFICHER L'ETAT DE LA VARIABLE "changed" GRACE A LA VARIABLE fichierhttpd
      debug:    
        msg: affichage de la valeur de la variable fichierhttpd = {{ fichierhttpd.changed }} 
    - name: REDEMARRAGE DU SERVICE HTTPD SI LE FICHIER httpd.conf A ETE MODIFIE
      service:   
        name: httpd
        state: reloaded
      when: fichierhttpd.changed 
    
- name: DEPLOIEMENT SERVEUR BASE DE DONNEES    
  hosts: db_servers
  become: true
  tasks: 
    - name: Installation de {{ db_package }} sur UBUNTU
      apt:
        name: "{{ db_package }}" 
        state: present
    - name: Affichage d'un message concernant le service
      debug:
        msg: Le service {{ db_service }}.service démarrera automatiquement 


- name: DEPLOIEMENT DU SERVEUR DE FICHIERS    
  hosts: file_servers
  become: true
  tasks:
    - name: INSTALLATION DU PAQUET "{{ samba_package }}" SUR rhel8-srv2
      package:  
        name: "{{ samba_package }}"
        state: present
    - name: INSTALLATION DU PAQUET "{{ nfs_package }}" sur rhel8-srv2
      dnf:
        name: "{{ nfs_package }}"
        state: present
  tags: files      

- name: DEPLOIEMENT DE TERRAFORM SUR UN SERVEUR UBUNTU
  hosts: management
  become: true
  tasks:
    - name: installation de terraform sur le serveur ubuntu-srv3
      unarchive:    
        src: https://releases.hashicorp.com/terraform/1.1.4/terraform_1.1.4_linux_amd64.zip
        dest: /usr/local/bin 
        remote_src: yes
        owner: root
        group: root
        mode: 0755










      

  


 






