--- # generallement on commence toujours par ces 3 tirets

- hosts: all    # liste des hosts.Correspond au PLAY.Ce PLAY va concernet toues les HOSTS (ici update et upgrade)
  tags: always # TAG ajouté au niveau du PLAY "hosts:all".Ce TAG concerne toutes les taches du play PAR HERITAGE.Le mot spécial "always" s'executera toujours sauf si on skip volontairement
  become: true  # Activation de SUDO.Tableau associatif dont l'équivalent en python est un dictionnaire {'become:'true'} ou avec un entier {'jambes':2}
  pre_tasks:    # declaration d'une LISTE de tâches.Le "pre" signifie que les tâches définies ici vont toujours avoir lieu avant les autres, même les rôles.

  - name: update index REPO et update des packages installés (RED HAT)
    dnf:
      update_cache: yes
      update_only: yes #DOC-ANSIBLE=>update seulement les paquets installés mais n'installe pas de paquets.
      state: latest
    when: ansible_distribution == "RedHat"
  
  - name: update index REPO et update des packages installés (UBUNTU)
    apt:
      update_cache: yes
      upgrade: full
    when: ansible_distribution == "Ubuntu"

# On déclare un PLAY qui concerne seulement le GROUPE "web_servers" de l'inventaire.Ici on installe apache et PHP pour les serveurs dans ce groupe

- hosts: web_servers # on reprend le nom exact du groupe dans la valeur [] du fichier inventory
  become: true
  tasks:
  
  - name: installation apache et PHP sur les serveurs web UBUNTU
    apt:               # on utilise le module apt
      name:                      
        - apache2 
        - libapache2-mod-php
      state: latest
    when: ansible_distribution in ["Debian", "Ubuntu"] # On peut écrire cette syntaxe si on a les 2 distributions dans le parc à gérer car les 2 utilisent "apt"
    
  - name: installation apache et PHP sur les serveurs web REDHAT
    dnf:                # on utilise le module DNF
      name: 
        - httpd # nom du paquet apache2 sous RHEL
        - php # nom du paquet PHP pour RHEL
      state: latest 
    when: ansible_distribution == "RedHat" and ansible_distribution_version == "8.5" # condition IF qui s'execute seulement si la distribution est RedHat ET la version est 8.5
  
- hosts: db_servers
  become: true
  tasks:

  - name: Installation de mariadb (REDHAT)
    dnf:
      name: mariadb
      state: latest
    when: ansible_distribution == 'RedHat'
    tags: ['redhat',db]
  
  - name: Installation de mariadb sur UBUNTU
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == 'Ubuntu'

- hosts: file_servers
  become: true
  tasks:

  - name: Installation du paquet SAMBA
    package:  # on utilise le module package car le paquet SAMBA server + client porte le même nom sur UBUNTU et REDHAT.
      name: samba
      state: present
    tags: samba # TAGS individuel qui ne concerne que cette TASK
  


 






