--- # generallement on commence toujours par ces 3 tirets
- hosts: all    # liste des hosts.Correspond au PLAY
  become: true  # Activation de SUDO.Tableau associatif dont l'équivalent en python est un dictionnaire {'become:'true'} ou avec un entier {'jambes':2}
  tasks:        # declaration d'une LISTE de tâches
 
 # UBUNTU SERVERS

  - name: update index repo # nom d'un TASK
    apt:        # on utilise le module apt
      update_cache: yes # équivalent à apt update
    when: ansible_distribution == "Ubuntu" # condition IF qui s'execute seulement si la distribution est UBUNTU
  - name: installation apache2
    apt:
      name: apache2
      state: latest #on veut s'assurrer d'avoir la dernière version d'apache2
    when: ansible_distribution == "Ubuntu"
  - name: installation php pour apache2
    apt:
      name: libapache2-mod-php
      state: latest
    when: ansible_distribution in ["Debian", "Ubuntu"] # On peut écrire cette syntaxe si on a les 2 distributions dans le parc à gérer car les 2 utilisent "apt"

# RHEL SERVER

  - name: update index repo RHEL
    dnf:        # on utilise le module DNF
      update_cache: yes # équivalent à dnf update
    when: ansible_distribution == "RedHat" and ansible_distribution_version == "8.5" # condition IF qui s'execute seulement si la distribution est RedHat et la version est 8.5
  - name: installation apache2 RHEL
    dnf:
      name: httpd # nom du paquet apache2 sous RHEL
      state: latest 
    when: ansible_distribution == "RedHat"
  - name: installation php pour RHEL
    dnf:
      name: php # nom du paquet PHP pour RHEL
      state: latest
    when: ansible_distribution == "RedHat"
    




