--- # generallement on commence toujours par ces 3 tirets
- hosts: all    # liste des hosts.Correspond au PLAY
  become: true  # Activation de SUDO.Tableau associatif dont l'équivalent en python est un dictionnaire {'become:'true'} ou avec un entier {'jambes':2}
  tasks:        # declaration d'une LISTE de tâches
  - name: update index repo # nom d'un TASK
    apt:        # on utilise le module apt
      update_cache: yes # équivalent à apt update
  - name: installation apache2
    apt:
      name: apache2
      state: latest #on veut s'assurrer d'avoir la dernière version d'apache2
  - name: installation php pour apache2
    apt:
      name: libapache2-mod-php
      state: latest




